{{- if and .Values.config.auth.enabled .Values.config.auth.secret.create -}}
{{- include "newrelic-super-agent.auth.secret.failTemplate" . -}}
---
kind: Secret
metadata:
  name: {{ include "newrelic-super-agent.auth.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
apiVersion: v1
data:
  {{ include "newrelic-super-agent.auth.secret.privateKey.key" . }}: {{ include "newrelic-super-agent.auth.secret.privateKey.data" . }}
  {{ include "newrelic-super-agent.auth.secret.clientId.key" . }}: {{ include "newrelic-super-agent.auth.secret.clientId.data" . }}
{{- end }}
